language: node_js
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
script:
  - npm run coverage
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
